all: primdraw

primdraw: main.primdraw.c
	gcc -o testogl main.primdraw.c -lGL -lglut

primscale: main.primscale.c
	gcc -o testogl main.primscale.c -lGL -lglut

winmod: main.winmod.c
	gcc -o testogl main.winmod.c -lGL -lglut

texture: main.texture.c
	gcc -o testogl main.texture.c -lGL -lglut

wireframes: main.wireframes.c
	gcc -o testogl main.wireframes.c -lGL -lglut

gluttext: main.gluttext.c
	gcc -o testogl main.gluttext.c -lGL -lglut